---
server:
  port: 41000
spring:
  application:
    name: swan-user
  profiles: dev1
eureka:
  instance:
    hostname: localhost
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:40000/eureka/
feign:
  hystrix:
    enabled: true

---
server:
  port: 41001
spring:
  application:
    name: swan-user
  profiles: dev2
eureka:
  instance:
    hostname: localhost
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:40000/eureka/