server:
  port: 30000
spring:
  application:
    name: swan-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        #git:
          #uri: https://github.com/cailonghao/hello-world-springcloud
          #username: 1719341471@qq.com
          #password: a923124582
eureka:
  instance:
    hostname: localhost
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:40000/eureka/