server:
  port: 22000
spring:
  application:
    name: swan-sleuth
eureka:
  instance:
    hostname: localhost
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:40000/eureka/